### ISSUE TITLE
Integrate Lightning/BLT

### ISSUE THREAD

**Issue by marceldobrica** [Actency/docker-apache-php#4]
Thank you for your hard work !

I have tried to use your solution with lightning, but it is difficult because drush, console are installed globally and lightning install them locally.... also php memory_limit is not enough for installing lightning using composer...
Drupal/commerce use bcmath extension and it might be useful to add it too. 
I think It might be useful a version without drush, console, xdebug ... or better make them optionally in environment variables in docker-compose.yml.... maybe also xdebug configuration for phpstorm...

Again thank you for your hard work! I'm using it and i have learned a lot from it!
I have tried to create an image from you Dockerfile but I wasn't able to... yet (hope)

**Comment by Renrhaf** [comment]
Hello @marceldobrica, I'm also using these images to meet my custom needs.
You can create your own Dockerfile from this one to include one or more php extensions :  
```
# Based on actency php 7.0 apache image
FROM actency/docker-apache-php:7.0

RUN docker-php-ext-install bcmath
```

See : 
https://github.com/Actency/docker-apache-php/blob/master/7.0/Dockerfile#L51

If you want a lightweight container without some tools, you could clone this repo code and tweak the Dockerfile to remove these lines for example : https://github.com/Actency/docker-apache-php/blob/master/7.0/Dockerfile#L101-L110

For the memory limit you have to edit the php.ini file : https://github.com/Actency/docker-apache-php/blob/88222ee40f6b45a424f8f70a4223d9eec784d80d/7.0-dev/config/php.ini#L396

**Comment by marceldobrica** [comment]
Thank you for your support.
